name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Teste com Gradle
        run: |
          ./gradlew test
      - name: Upload artefatos de teste
        uses: actions/upload-artifact@v3
        with:
          name: relatorio-testes
          path: build/reports/tests/test/

  build:
    runs-on: ubuntu-latest

    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build com gradle
        run: |
          ./gradlew clean build
      - name: Upload artefatos de build
        uses: actions/upload-artifact@v3
        with:
          name: arquivo-jar
          path: gradle/wrapper/*.jar